### ISSUE TITLE
Delete button doesn't work

### ISSUE THREAD

**Issue by jbehaege** [vahicode/website#11]
The delete button on the page of the pictures doesn't work. 
It's possible to delete eyes, but not the pictures.

**Comment by joostdecock** [comment]
I am unable to reproduce this. While the table of pictures doesn't update until a refresh, the picture is removed.

Perhaps you can tell me what picture it is you are trying to remove?

**Comment by jbehaege** [comment]
Last week I couldn't remove any of the pictures, but now it works. 
Only the eyes (no pictures) 29 and 30 are unremovable, but this is not really an issue. Thank you.
