### ISSUE TITLE
Add new eye after deleting old eye

### ISSUE THREAD

**Issue by jbehaege** [vahicode/website#12]
I can't manage to add a new eye to a picture after deleting an old eye. 
I can place the grid onto the image after selecting the image and place them on active but the eyes are not saved in the system.

**Comment by joostdecock** [comment]
This should be resolved now for any new eyes you remove, as the pictures linked to it will have that linked removed.

However, for the picture that still has a link to a previously removed eye, you will either have to remove the picture, or give me its ID so I can manually reset it.
